baseURL = "https://cheme.github.io/"
languageCode = "en-us"
title = "Émeric misexperiment blog"
theme = "ananke"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = ""
  description = "Blogging about personal projects"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/cheme"
  linkedin = "https://www.linkedin.com/in/emericchevalier"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/screenshot.png"
